spring:
  application:
    name: ambev-test

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/ambev_db
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
