spring:
  security.oauth2.resourceserver:
    jwt:
      issuer-uri: "${KEYCLOAK_URL:http://localhost:8081}/auth/realms/${KEYCLOAK_REALM:CarshopKeycloak}"
      jwk-set-uri : "${KEYCLOAK_URL:http://localhost:8081}/auth/realms/${KEYCLOAK_REALM:CarshopKeycloak}/protocol/openid-connect/certs"
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/carshop_db
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}

server:
  port: 8080

